### ISSUE TITLE
Bij terug naar vragen alle gedane vragen aanbieden

### ISSUE THREAD

**Issue by pboot** [marijnkoolen/reading-impact-questionnaire#1]
Ik  denk dat het geval dat iemand honderden vragen heeft beantwoord vrij theoretisch is, en zo ja, dan moet die persoon maar door wat meer vragen heen. Ik zou ze gewoon allemaal tonen. 
Houd je trouwens een tijdstip bij waarop een zin is beoordeeld? Of is er een inherente volgorde van de zinnen waarin je ze toont?

**Comment by marijnkoolen** [comment]
Knop en view toegevoegd.
