### ISSUE TITLE
Nieuwe user ziet lijst met zinnen van vorige user

### ISSUE THREAD

**Issue by pboot** [marijnkoolen/reading-impact-questionnaire#10]
Chrome op Windows. 
Ik ben ingelogd geweest als kva851, die 55 zinnen heeft beoordeeld. 
Nu log ik in als byy041, die 1 zin heeft beoordeeld. 
Maar ik kom terecht in het overzichtsscherm van kva851, ook al zijn diens zinnen daar terecht rood en niet groen. 
Zie het plaatje.

![image](https://user-images.githubusercontent.com/4853271/51487990-ad3fea80-1da4-11e9-9d3b-ff9799ad354c.png)

**Comment by marijnkoolen** [comment]
De localStorage werd niet opgeruimd als er tussen gebruikers geschakeld werd (om te zorgen dat opnieuw aanmelden met zelfde ID de gemaakte responses onthoudt). Nu filter ik responses in localStorage a.d.h.v. wie er ingelogd is.
