### ISSUE TITLE
Aanpassingen 'gevoelens' vragen

### ISSUE THREAD

**Issue by pboot** [marijnkoolen/reading-impact-questionnaire#2]
Ik stel voor de vraag maar één keer te stellen, met als opties 
- prettig
- onprettig
- zowel prettig als onprettig
- niet van toepassing, neutraal, onduidelijk

Er is inderdaad wel een onderscheid tussen neutraal en onduidelijk maar ik denk dat in de praktijk het vaak lastig zal zijn.

**Comment by marijnkoolen** [comment]
Vraag slechts één keer.

Nieuwe formulering: Als er bij de reviewer in deze zin sprake is van emotionele impact, narratieve gevoelens, of gevoelens m.b.t. de stijl, zijn deze dan:

**Comment by marijnkoolen** [comment]
Fix with commit [54da2f1](https://github.com/marijnkoolen/reading-impact-questionnaire/commit/54da2f1cfd1bd87a5d96e3980d66c7c40a4fd25f).
