### ISSUE TITLE
'Is er (in deze zin) sprake van' - formulering aanpassen in: 'Blijken uit deze zin'

### ISSUE THREAD

**Issue by pboot** [marijnkoolen/reading-impact-questionnaire#3]

**Comment by marijnkoolen** [comment]
Volgens mij moeten we de precieze vragen uitschrijven, want de formulering die je voorstelt werkt volgens niet overal.

Voorbeelden:

Emotionele impact:
- Huidige formulering: Is er in deze zin sprake van emotionele impact op de reviewer?
- Nieuwe formulering: Blijken uit deze zin emotionele impact op de reviewer?

Narratieve gevoelens:
- Huidige formulering: Is er sprake van narratieve gevoelens bij de reviewer?
- Nieuwe formulering: Blijken uit deze zin narratieve gevoelens bij de reviewer?

Stijl:
- Huidige formulering: Is er bij de reviewer sprake van gevoelens m.b.t. de stijl?
- Nieuwe formulering: Blijken uit deze zin gevoelens van de reviewer m.b.t. de stijl?

Reflectie:
- Huidige formulering: Is er bij de reviewer sprake van reflectie?
- Nieuwe formulering: Blijken uit deze zin reflectie van de reviewer?

**Comment by marijnkoolen** [comment]
Bespreking:

- emotionele impact: Blijkt uit deze zin emotionele impact op de reviewer
- narratieve gevoelens: Blijken uit deze zin narratieve gevoelens bij de reviewer?
- stijl: Geeft de reviewer deze zin blijk van gevoelens m.b.t. de stijl?
- reflectie: Blijkt uit deze zin reflectie van de reviewer?
