### ISSUE TITLE
Inrichten web pagina met meer toelichting

### ISSUE THREAD

**Issue by pboot** [marijnkoolen/reading-impact-questionnaire#4]

**Comment by pboot** [comment]
Inhoud van de pagina: 
            <div className="readme-header">
                <h1>Beoordelen van Impact van Lezen in Boekrecensies: een beetje achtergrond</h1>
            </div>
            <div className="readme-background">
                <p>
                    Literatuurwetenschappers studeren al lang op de vraag hoe verhalen een 
                    effect op lezers kunnen hebben. Voorheen was dat een vraag die bij gebrek aan 
                    gegevens moeilijk te beantwoorden was. Want hoe moest je komen aan informatie over 
                    wat lezers dachten van boeken, van hun plots, hun stijl en personages? Er was 
                    informatie uit recensies van professionele boekbesprekers, soms lieten mensen zich in brieven 
                    of dagboeken uit over wat ze hadden gelezen, en een enkele keer stond er een 
                    dikke streep in de kantlijn van een bibliotheekboek.   
                </p>
                <p>Tegenwoordig is die situatie helemaal anders: talloze lezers laten meningen 
                    achter op bol.com, op hebban.nl, op hun eigen weblogs, enzovoort. Onderzoekers 
                    hebben toegang tot een overvloed aan meningen over boeken. We beginnen 
                    onderzoek te zien dat van deze bronnen gebruik maakt.</p>
                <p>Nu is er echter een heel andere uitdaging: er zijn ontzettend veel online 
                    reviews beschikbaar, meer dan onderzoekers ooit zouden kunnen lezen. Het 
                    onderzoek waar wij mee bezig zijn wil een manier ontwikkelen waarmee de 
                    computer kan bepalen welke vorm van impact van een boek in een bepaalde 
                    online bespreking aan de orde is.</p>
                <p>We maken daarvoor een verzameling regels die bepaalde frases koppelen aan 
                    een bepaalde vorm van impact. Twee makkelijke voorbeelden: het woord 
                    <i>meeslepend</i> wordt gekoppeld aan narratieve gevoelens, de frase 
                    <i>schitterende schrijfstijl</i> aan gevoelens over stijl. Maar er zijn ook veel 
                    woorden en frases die heel verschillende dingen kunnen betekenen. Slaat het 
                    woord <i>geraakt</i> op een lezer die is geraakt door het verhaal of op een boef, 
                    geraakt door een politiekogel? Daarom moeten we de regels checken, en daarvoor 
                    hebben we mensen nodig die aangeven of de uitkomst klopt. De computer past de 
                    regels toe op een collectie zinnen en "berekent" welke vorm van lees-impact 
                    in die zinnen wordt uitgedrukt; onze informanten geven aan hoe zij die zinnen 
                    zouden lezen. We leggen dan de mening van de informanten naast die van de 
                    computer; als de twee overeenstemmen dan kan de computer, met behulp van die 
                    regels, ook andere reviews "lezen". 
                </p>
                <p>Vooralsnog doen we dit onderzoek puur uit wetenschappelijke nieuwsgierigheid.
                    Maar er zijn ook interessante mogelijkheden om dit onderzoek toe te passen. 
                    Je zou je kunnen voorstellen dat je op een dag in staat bent om lezers 
                    aanbevelingen te doen op basis van kennis van de impact van verschillende boeken. </p>
                <p>Voor het moment is onze volgende vraag veel simpeler: als we de impact-aspecten betrouwbaar kunnen 
                    bepalen, kunnen we dan ook uitvinden of verschillende genres boeken corresponderen 
                    met verschillende vormen van impact?   
                </p>
         </div>

**Comment by marijnkoolen** [comment]
Uitgebreidere uitleg nu opgenomen in ReadmeMore.js.
