### ISSUE TITLE
Toelichting bij de vragen

### ISSUE THREAD

**Issue by pboot** [marijnkoolen/reading-impact-questionnaire#5]
Emotionele impact: elke (tijdelijke of blijvende) emotionele reactie tijdens of na het lezen, of dit nu betrekking heeft op het boek als geheel, de karakters, de auteur, de stijl, aspecten van de wereld die het boek beschrijft, of enig ander aspect. Deze gevoelens mogen positief of negatief zijn, sterk of zwak. Het gaat echter **niet** om gevoelens zoals verveling, waar het boek kennelijk niet het gewenste effect heeft.  

Narratieve gevoelens: elk gevoel met betrekking tot de verhaalwereld en de personages. Het mag gaan om gevoelens van opgaan in het verhaal of de verhaalwereld of gevoelens voor personages, zoals bewondering, identificatie of medelijden.

Gevoelens met betrekking tot de stijl: elk gevoel dat betrekking heeft op de aesthetische aspecten van de tekst, zoals bewondering, waardering, verrassing of vervreemding.

Reflectie: gedachten, inzichten en mijmeringen over jezelf, de personages, het boek of de wereld. 

Prettig/onprettig: Het gaat hier om de gevoelens van de reviewer! Een 'afschuwelijke moord' is iets negatiefs, maar kan het beginpunt zijn voor een mooi verhaal. 'Prettig' is wat je aanzet tot lezen, 'onprettig' is waardoor je met lezen wilt stoppen.

**Comment by marijnkoolen** [comment]
Verwerkt in commit [0ab8a26](https://github.com/marijnkoolen/reading-impact-questionnaire/commit/0ab8a26830454372471e13a39579c69422e0b710).

**Comment by marijnkoolen** [comment]
Dank! Aangepast in commit [0ab8a26](https://github.com/marijnkoolen/reading-impact-questionnaire/commit/22f6d298dd11ecda37852b3af3aa899cf3045a20).
