### ISSUE TITLE
Add option for registering email address to be asked for additional research.

### ISSUE THREAD

**Issue by marijnkoolen** [marijnkoolen/reading-impact-questionnaire#7]

**Comment by marijnkoolen** [comment]
Ik zie twee opties:

1. we bieden een input om email in te vullen en slaan die op in de database.
2. we noemen onze emailadressen en geven aan dat mensen ons kunnen mailen als ze op de hoogte gehouden willen worden.

De tweede is een iets hogere drempel, maar simpeler en persoonlijker (en wekt wellicht minder argwaan, e.g. "wat betekent het als ik mijn emailadres in een database laat opslaan?").

**Comment by pboot** [comment]
Ja, 2 lijkt me het beste

**Comment by marijnkoolen** [comment]
Verwerkt.
