### ISSUE TITLE
Typeerror na 'toon al mijn beoordelingen'

### ISSUE THREAD

**Issue by pboot** [marijnkoolen/reading-impact-questionnaire#9]
In Firefox op windows (maar zie het nu ook op Chrome): 
- ingelogd als kva 851
- klik op 'toon al mijn beoordelingen' (toont inderdaad beoordeelde zinnen)
- klik daarna op 'nog te beoordelen zinnen. Dan gebeurt er niets en de log toont het volgende (dat doen de andere knoppen ook):

 [Berichtdetails tonen/verbergen] TypeError: FormActions.getLocalSentences(...) is null[Meer info] formActions.js:89:23
sendComments
formActions.js:89:23
checkComments
formActions.js:80:12
changeView
formActions.js:31:8
backToQuestionnaire
AllJudgements.js:73:8
backToQuestionnaire self-hosted:990:17 backToQuestionnaire self-hosted:1087:17 ReactErrorUtils.invokeGuardedCallback
ReactErrorUtils.js:70
executeDispatch
EventPluginUtils.js:89
executeDispatchesInOrder
EventPluginUtils.js:112
executeDispatchesAndRelease
EventPluginHub.js:44
executeDispatchesAndReleaseTopLevel
EventPluginHub.js:55
forEach self-hosted:268:13 forEachAccumulated
forEachAccumulated.js:25
processEventQueue
EventPluginHub.js:231
runEventQueueInBatch
ReactEventEmitterMixin.js:18
handleTopLevel
ReactEventEmitterMixin.js:29
handleTopLevelImpl
ReactEventListener.js:73
perform
Transaction.js:138
batchedUpdates
ReactDefaultBatchingStrategy.js:63
batchedUpdates
ReactUpdates.js:98
dispatchEvent
ReactEventListener.js:150
dispatchEvent self-hosted:1030:17 

- daarna kan ik niets meer op deze site, ook na opnieuw opstarten van de browser ziet het er zo uit: 
![image](https://user-images.githubusercontent.com/4853271/51397623-df054700-1b41-11e9-9b19-711b19b9fd71.png)

- alle knoppen geven als resultaat hetzelfde als hierboven (en doen niets)

**Comment by pboot** [comment]
Probleem valt op te lossen door het leeg maken van de browser storage. Maar dat kunnen we van onze gebruikers natuurlijk niet vragen. 
Nu slaat mijn browser, lijkt het, ook mijn id niet meer op? Vreemd.

**Comment by marijnkoolen** [comment]
Opgelost in commit [7173e88](https://github.com/marijnkoolen/reading-impact-questionnaire/commit/7173e88f19275df4494685f18626ec5ff82c4919).
